### ISSUE TITLE
put a small DO cross in inst/data

### ISSUE THREAD

**Issue by rcorty** [rcorty/vqtl2#13]
really small so as not to cause a problem on CRAN

**Comment by fboehm** [comment]
would it be worthwhile to use DOex.zip (or another data set) from https://github.com/rqtl/qtl2data? Maybe the Recla data (in the same repo) is more interesting, and contains data from all chromosomes.

Its README (https://github.com/rqtl/qtl2data/tree/master/DOex) gives code for downloading and using the DOex data set the rqtl/qtl2. If you use it, you wouldn't need to add the actual data to the vqtl2 package, since you could just instruct users to download it directly from Github (ie, from the qtl2data repo).

**Comment by rcorty** [comment]
Sorry, I should have explained this better.  The main reason I want to put data in vqtl2 is so that the automated tests are meaningful.  qtl2 has an F2 cross, so I use that in the tests.  But for the tests on a DO cross, the data gets downloaded from the internet.  Ultimately, I'd like to have some sample data from each type of cross that vqtl2 will be able to handle.

The trick will be to trim the data down in the right way to preserve all the corner cases (which need testing), while making the tests relatively fast.

**Comment by rcorty** [comment]
Wow, yeah, qtl2data looks great.  Thanks for pointing this out.

**Comment by rcorty** [comment]
put it in /data
